<ItemLabel@Label>:
    font_size: '25sp'
    halign: 'left'
    valign: 'middle'
    text_size: self.size

ScreenManager:
    Main_menu:
    Menu1:
    Menu2:
    Menu3:
    Menu4:
    Menu5:
    Menu6:
    Menu7:


<Main_menu>:
    name: 'Main_menu'
    BoxLayout:
        orientation: 'vertical'
        spacing: 5
        padding: [50, 10]

        Button:
            text: 'Гамбургенр'
            on_press: 
                root.manager.current = 'Menu1'

        Button:
            text: 'Гамбургенр чорний'
            on_press:
                root.manager.current = 'Menu2'

        Button:
            text: 'Котлета в тісті'
            on_press:
                root.manager.current = 'Menu3'

        Button:
            text: 'Котлета по-київськи'
            on_press:
                root.manager.current = 'Menu4'

        Button:
            text: 'Фарш на періжки (10 Кг)'
            on_press:
                root.manager.current = 'Menu5'

        Button:
            text: 'Биток (Кг)'
            on_press:
                root.manager.current = 'Menu6'

        Button:
            text: 'Хачапурі (10 Кг)'
            on_press:
                root.manager.current = 'Menu7'




<Menu1>:
    name: 'Menu1'
    menu1_input: text_input
    menu1_ingr1: menu1_ingr1
    menu1_ingr2: menu1_ingr2
    menu1_ingr3: menu1_ingr3
    GridLayout:
        rows: 3



        AnchorLayout:
            size_hint: 1, 0.15

            TextInput:
                id: text_input
                font_size: '45sp'
                multiline: False
                input_type: 'number'
                input_filter: 'int'

        GridLayout:
            cols: 2

            BoxLayout:
                orientation: 'vertical'
                padding: [30, 0, 0, 0]

                ItemLabel:
                    text: 'Філе'

                ItemLabel:
                    text: 'Мясообріз'

                ItemLabel:
                    text: 'Цибуля'


            BoxLayout:
                orientation: 'vertical'
                size_hint: 0.5, 1

                ItemLabel:
                    id: menu1_ingr1
                    text: '0'

                ItemLabel:
                    id: menu1_ingr2
                    text: '0'

                ItemLabel:
                    id: menu1_ingr3
                    text: '0'


        BoxLayout:
            size_hint: 0.9, 0.15
            padding: [30, 0, 30, 20]

            Button:
                text: 'Розрахувати'
                font_size: 20
                on_release:
                    root.calc_menu1()
            Button:
                text: 'В меню'
                font_size: 30
                on_press:
                    root.manager.current = 'Main_menu'

<Menu2>:
    name: 'Menu2'
    menu2_input: text_input
    menu2_ingr1: menu2_ingr1
    menu2_ingr2: menu2_ingr2
    menu2_ingr3: menu2_ingr3
    GridLayout:
        rows: 3



        AnchorLayout:
            size_hint: 1, 0.15

            TextInput:
                id: text_input
                font_size: '45sp'
                multiline: False
                input_type: 'number'
                input_filter: 'int'

        GridLayout:
            cols: 2

            BoxLayout:
                orientation: 'vertical'
                padding: [30, 0, 0, 0]

                ItemLabel:
                    text: 'Філе'

                ItemLabel:
                    text: 'Мясообріз'

                ItemLabel:
                    text: 'Цибуля'


            BoxLayout:
                orientation: 'vertical'
                size_hint: 0.5, 1

                ItemLabel:
                    id: menu2_ingr1
                    text: '0'

                ItemLabel:
                    id: menu2_ingr2
                    text: '0'

                ItemLabel:
                    id: menu2_ingr3
                    text: '0'


        BoxLayout:
            size_hint: 0.9, 0.15
            padding: [30, 0, 30, 20]

            Button:
                text: 'Розрахувати'
                font_size: 20
                on_release:
                    root.calc_menu2()
            Button:
                text: 'В меню'
                font_size: 30
                on_press:
                    root.manager.current = 'Main_menu'

<Menu3>:
    name: 'Menu3'
    menu3_input: text_input
    menu3_ingr1: menu3_ingr1
    menu3_ingr2: menu3_ingr2
    menu3_ingr3: menu3_ingr3
    GridLayout:
        rows: 3



        AnchorLayout:
            size_hint: 1, 0.15

            TextInput:
                id: text_input
                font_size: '45sp'
                multiline: False
                input_type: 'number'
                input_filter: 'int'

        GridLayout:
            cols: 2

            BoxLayout:
                orientation: 'vertical'
                padding: [30, 0, 0, 0]

                ItemLabel:
                    text: 'Мясообріз (Філе)'

                ItemLabel:
                    text: 'Сало'

                ItemLabel:
                    text: 'Цибуля'


            BoxLayout:
                orientation: 'vertical'
                size_hint: 0.5, 1

                ItemLabel:
                    id: menu3_ingr1
                    text: '0'

                ItemLabel:
                    id: menu3_ingr2
                    text: '0'

                ItemLabel:
                    id: menu3_ingr3
                    text: '0'


        BoxLayout:
            size_hint: 0.9, 0.15
            padding: [30, 0, 30, 20]

            Button:
                text: 'Розрахувати'
                font_size: 20
                on_release:
                    root.calc_menu3()
            Button:
                text: 'В меню'
                font_size: 30
                on_press:
                    root.manager.current = 'Main_menu'
                
<Menu4>:
    name: 'Menu4'
    menu4_input: text_input
    menu4_ingr1: menu4_ingr1
    menu4_ingr2: menu4_ingr2
    GridLayout:
        rows: 3



        AnchorLayout:
            size_hint: 1, 0.15

            TextInput:
                id: text_input
                font_size: '45sp'
                multiline: False
                input_type: 'number'
                input_filter: 'int'

        GridLayout:
            cols: 2

            BoxLayout:
                orientation: 'vertical'
                padding: [30, 0, 0, 0]

                ItemLabel:
                    text: 'Філе'

                ItemLabel:
                    text: 'Сіль'



            BoxLayout:
                orientation: 'vertical'
                size_hint: 0.5, 1

                ItemLabel:
                    id: menu4_ingr1
                    text: '0'

                ItemLabel:
                    id: menu4_ingr2
                    text: '0'


        BoxLayout:
            size_hint: 0.9, 0.15
            padding: [30, 0, 30, 20]

            Button:
                text: 'Розрахувати'
                font_size: 20
                on_release:
                    root.calc_menu4()
            Button:
                text: 'В меню'
                font_size: 30
                on_press:
                    root.manager.current = 'Main_menu'

                
<Menu5>:
    name: 'Menu5'
    menu5_input: text_input
    menu5_ingr1: menu5_ingr1
    menu5_ingr2: menu5_ingr2
    menu5_ingr3: menu5_ingr3
    menu5_ingr4: menu5_ingr4
    GridLayout:
        rows: 3



        AnchorLayout:
            size_hint: 1, 0.15

            TextInput:
                id: text_input
                font_size: '45sp'
                multiline: False
                input_type: 'number'
                input_filter: 'int'

        GridLayout:
            cols: 2

            BoxLayout:
                orientation: 'vertical'
                padding: [30, 0, 0, 0]

                ItemLabel:
                    text: 'Мясообріз (хляки)'

                ItemLabel:
                    text: 'Цибуля'

                ItemLabel:
                    text: 'Перець чорний'

                ItemLabel:
                    text: 'Сіль'

            BoxLayout:
                orientation: 'vertical'
                size_hint: 0.5, 1

                ItemLabel:
                    id: menu5_ingr1
                    text: '0'

                ItemLabel:
                    id: menu5_ingr2
                    text: '0'

                ItemLabel:
                    id: menu5_ingr3
                    text: '0'

                ItemLabel:
                    id: menu5_ingr4
                    text: '0'


        BoxLayout:
            size_hint: 0.9, 0.15
            padding: [30, 0, 30, 20]

            Button:
                text: 'Розрахувати'
                font_size: 20
                on_release:
                    root.calc_menu5()
            Button:
                text: 'В меню'
                font_size: 30
                on_press:
                    root.manager.current = 'Main_menu'



<Menu6>:
    name: 'Menu6'
    menu6_input: text_input
    menu6_ingr1: menu6_ingr1
    menu6_ingr2: menu6_ingr2
    GridLayout:
        rows: 3



        AnchorLayout:
            size_hint: 1, 0.15

            TextInput:
                id: text_input
                font_size: '45sp'
                multiline: False
                input_type: 'number'
                input_filter: 'int'

        GridLayout:
            cols: 2

            BoxLayout:
                orientation: 'vertical'
                padding: [30, 0, 0, 0]

                ItemLabel:
                    text: 'Філе'

                ItemLabel:
                    text: 'Мясообріз'



            BoxLayout:
                orientation: 'vertical'
                size_hint: 0.5, 1

                ItemLabel:
                    id: menu6_ingr1
                    text: '0'

                ItemLabel:
                    id: menu6_ingr2
                    text: '0'


        BoxLayout:
            size_hint: 0.9, 0.15
            padding: [30, 0, 30, 20]

            Button:
                text: 'Розрахувати'
                font_size: 20
                on_release:
                    root.calc_menu6()
            Button:
                text: 'В меню'
                font_size: 30
                on_press:
                    root.manager.current = 'Main_menu'


<Menu7>:
    name: 'Menu7'
    menu7_input: text_input
    menu7_ingr1: menu7_ingr1
    menu7_ingr2: menu7_ingr2
    menu7_ingr3: menu7_ingr3
    menu7_ingr4: menu7_ingr4
    menu7_ingr5: menu7_ingr5
    menu7_ingr6: menu7_ingr6
    GridLayout:
        rows: 3



        AnchorLayout:
            size_hint: 1, 0.15

            TextInput:
                id: text_input
                font_size: '45sp'
                multiline: False
                input_type: 'number'
                input_filter: 'int'

        GridLayout:
            cols: 2

            BoxLayout:
                orientation: 'vertical'
                padding: [30, 0, 0, 0]

                ItemLabel:
                    text: 'Мясообріз (хляки)'

                ItemLabel:
                    text: 'Цибуля'

                ItemLabel:
                    text: 'Морква'

                ItemLabel:
                    text: 'Сіль'

                ItemLabel:
                    text: 'Перець чорний'

                ItemLabel:
                    text: 'Эвропейська приправа'


            BoxLayout:
                orientation: 'vertical'
                size_hint: 0.5, 1

                ItemLabel:
                    id: menu7_ingr1
                    text: '0'

                ItemLabel:
                    id: menu7_ingr2
                    text: '0'

                ItemLabel:
                    id: menu7_ingr3
                    text: '0'

                ItemLabel:
                    id: menu7_ingr4
                    text: '0'

                ItemLabel:
                    id: menu7_ingr5
                    text: '0'

                ItemLabel:
                    id: menu7_ingr6
                    text: '0'


        BoxLayout:
            size_hint: 0.9, 0.15
            padding: [30, 0, 30, 20]

            Button:
                text: 'Розрахувати'
                font_size: 20
                on_release:
                    root.calc_menu7()
            Button:
                text: 'В меню'
                font_size: 30
                on_press:
                    root.manager.current = 'Main_menu'

